### ISSUE TITLE
Compiling wxWidgets-3.1.4 on Windows with MinGW

### ISSUE THREAD

**Issue by qgai** [huckor/wxwidgets-vscode#1]
If anyone is having trouble compiling here is solution that worked for me for minimal sample. Added compiler flags are marked with "//"

```
"-lwxmsw31u_core", //just change 30 to 31
"-lwxbase31u", //same as above
"-lwxpng",
"-lwxregexu", //
"-lwxzlib", //
"-lcomdlg32",
"-lgdi32",
"-lcomctl32",
"-lole32",
"-loleaut32",
"-ldmoguids",
"-luuid",
"-lwinspool",
"-luxtheme", //
"-loleacc", //
"-lshlwapi", //
"-lversion",//
"-lz"
```

-lshlwapi and -lversion is needed because of a change they made. Doublemax from forum.wxwidgets.org helped and gave answer:

> From <wx>/docs/changes.txt:
> Changes in behaviour which may result in build errors
>  -----------------------------------------------------
> - wxMSW now requires linking with shlwapi.lib and version.lib. This is done
>  automatically in most cases, but if you use a static build of the library
> with a non-MSVC compiler such as MinGW and do not use wx-config, then you
> will need to add these libraries to your make or project files yourself.

Also huge, huge thanks to @huckor for this repo!

**Comment by pcatrobrouillet** [comment]
Thanks.
I forgot the shlwapi and version libs and wasted some time. Your issue helped.

Also, indeed, huge thanks to @huckor! This tutorial is awesome!

**Comment by huckor** [comment]
@QGAI thanks for support. I created separate branch for wx 3.0.5 and wx 3.1.4
