### ISSUE TITLE
Error when compiling on Windows 11 using VSCode

### ISSUE THREAD

**Issue by graham-eisele** [huckor/wxwidgets-vscode#13]
I am getting the following errors when trying to compile using vscode on windows 11. I followed the instructions to compile first.

````Executing task: g++ -IC:\Users\graha\Documents\wxwidgets-vscode\dep\win\lib\gcc_lib\mswu -IC:\Users\graha\Documents\wxwidgets-vscode\dep\win\include -c $( dir -Path C:\Users\graha\Documents\wxwidgets-vscode\src -Filter *.cpp -Recurse | %{$_.FullName} ) -g -Wall -D_WINDOWS -D_UNICODE -D__WXMSW__ -DNDEBUG -DNOPCH 

 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: Move-Item -Path C:\Users\graha\Documents\wxwidgets-vscode\*.o -Destination C:\Users\graha\Documents\wxwidgets-vscode\out -Force 

 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: g++ -LC:\Users\graha\Documents\wxwidgets-vscode\dep\win\lib\gcc_lib -Lc:\mingw-w64\mingw64\x86_64-w64-mingw32\lib -mwindows -static C:\Users\graha\Documents\wxwidgets-vscode\out\**.o -o C:\Users\graha\Documents\wxwidgets-vscode\out\myapp.exe -lwxmsw31u_core -lwxbase31u -lwxpng -lcomdlg32 -lgdi32 -lcomctl32 -lole32 -loleaut32 -ldmoguids -luuid -lwinspool -lz -lwxregexu -lwxzlib -luxtheme -loleacc -lshlwapi -lversion 

C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxmsw31u_core: No such file or directory
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxbase31u: No such file or directory   
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lz: No such file or directory
collect2.exe: error: ld returned 1 exit status

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command g++ -LC:\Users\graha\Documents\wxwidgets-vscode\dep\win\lib\gcc_lib -Lc:\mingw-w64\mingw64\x86_64-w64-mingw32\lib -mwindows -static C:\Users\graha\Documents\wxwidgets-vscode\out\**.o -o C:\Users\graha\Documents\wxwidgets-vscode\out\myapp.exe -lwxmsw31u_core -lwxbase31u -lwxpng -lcomdlg32 -lgdi32 -lcomctl32 -lole32 -loleaut32 -ldmoguids -luuid -lwinspool -lz -lwxregexu -lwxzlib -luxtheme -loleacc -lshlwapi -lversion" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
 * ````

**Comment by huckor** [comment]
Seems linker is not able to locate mandatory wxwidgets libraries.
Could you check if directory C:\Users\graha\Documents\wxwidgets-vscode\dep\win\lib\gcc_lib contains files libwxmsw31u_core.a and libwxbase31u.a?
If this files are missing then something happened during compilation of wxwidgets libraries.

**Comment by graham-eisele** [comment]
It was because I was using the newest version rather than 3.1.6. Though I got the error 

`*  Executing task: g++ -LC:\Users\graha\Documents\wxwidgets-vscode\dep\win\lib\gcc_lib -Lc:\mingw-w64\mingw64\x86_64-w64-mingw32\lib -mwindows -static C:\Users\graha\Documents\wxwidgets-vscode\out\**.o -o C:\Users\graha\Documents\wxwidgets-vscode\out\myapp.exe -lwxmsw31u_core -lwxbase31u -lwxpng -lcomdlg32 -lgdi32 -lcomctl32 -lole32 -loleaut32 -ldmoguids -luuid -lwinspool -lz -lwxregexu -lwxzlib -luxtheme -loleacc -lshlwapi -lversion 

C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lz: No such file or directory
collect2.exe: error: ld returned 1 exit status
`

When I remove the `-lz` flag it does compile though.

**Comment by huckor** [comment]
Did you use wxwidgets 3.2.2.1 or different version?

**Comment by huckor** [comment]
Updated project to compile with wxWidgets 3.2.3. Closing this issue.
