### ISSUE TITLE
I can not compile my apps

### ISSUE THREAD

**Issue by gabrielrsep** [huckor/wxwidgets-vscode#14]
![Captura de tela 2024-04-15 231922](https://github.com/huckor/wxwidgets-vscode/assets/28923770/34781ce7-b0b6-4122-8ca1-8651e39e1d8d)
this error happens

**Comment by huckor** [comment]
Looks like your system does not contains lib zip.
Try to remove line showed on screenshot below. Open and edit file .vscode/tasks.json.
<img width="708" alt="Screenshot 2024-04-16 at 14 01 14" src="https://github.com/huckor/wxwidgets-vscode/assets/20068605/fb292761-9519-457c-a1d9-4baffaeaa635">

**Comment by gabrielrsep** [comment]
Well, this works! 👍 But how this affect my compiled apps? In what cases wxWidgts uses this lib?

**Comment by huckor** [comment]
Sees to me this lib is not required anymore because wx uses wxzlib instead. Will remove this dependency for next release of this project.
