### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by ariedeleen** [huckor/wxwidgets-vscode#3]
Is it possible to compile multiple cpp and/or header files?
Now when there is another or more cpp file(s) in the 
scr folder. There is an error:
g++.exe: fatal error: cannot specify -o with -c, -S or -E with multiple files
compilation terminated.

thanx in advance, keep up the good work...

**Comment by paineliu** [comment]
cmake_minimum_required(VERSION 3.12)
project(wx_test)

set(CMAKE_C_STANDARD 11)

include_directories(./src)
include_directories(./dep/win/lib/gcc_lib/mswu)
include_directories(./dep/win/include)

add_definitions(-D_WINDOWS)
add_definitions(-D_UNICODE)
add_definitions(-D__WXMSW__)
add_definitions(-DNDEBUG)
add_definitions(-DNOPCH)
add_definitions(-g)
add_definitions(-Wall)

link_directories(./dep/win/lib/gcc_lib)
link_directories(c:/mingw64/x86_64-w64-mingw32/lib)

SET(WX_PROJ_SRC
        ./src/customdlg.cpp
        ./src/main.cpp
        )


add_executable(${PROJECT_NAME} ${WX_PROJ_SRC})

set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS -Wl,--subsystem,windows)

target_link_libraries(${PROJECT_NAME} -lwxmsw31u_core)
target_link_libraries(${PROJECT_NAME} -lwxbase31u)
target_link_libraries(${PROJECT_NAME} -lwxpng)
target_link_libraries(${PROJECT_NAME} -lcomdlg32)
target_link_libraries(${PROJECT_NAME} -lgdi32)
target_link_libraries(${PROJECT_NAME} -lcomctl32)
target_link_libraries(${PROJECT_NAME} -lole32)
target_link_libraries(${PROJECT_NAME} -loleaut32)
target_link_libraries(${PROJECT_NAME} -ldmoguids)
target_link_libraries(${PROJECT_NAME} -luuid)
target_link_libraries(${PROJECT_NAME} -lwinspool)
target_link_libraries(${PROJECT_NAME} -lz)
target_link_libraries(${PROJECT_NAME} -lwxregexu)
target_link_libraries(${PROJECT_NAME} -lwxzlib)
target_link_libraries(${PROJECT_NAME} -luxtheme)
target_link_libraries(${PROJECT_NAME} -loleacc)
target_link_libraries(${PROJECT_NAME} -lshlwapi)
target_link_libraries(${PROJECT_NAME} -lversion)

**Comment by huckor** [comment]
Hey. Try to use branch add-multiple-cpp-files-support. It's currently on testing stage for Linux and Windows but should works. Let me know if it's working for you.

**Comment by huckor** [comment]
Multiple source code files and folders added. For wxwidgets 3.1.4 use master branch or release wx_3.1.4_v2. For wxWidgets 3.0.5 use develop_wx_3.0.5 or release wx_3.0.5_v2.
