### ISSUE TITLE
Raspberry Pi Linux build?

### ISSUE THREAD

**Issue by ericmandm** [huckor/wxwidgets-vscode#5]
Hello, 
I tried to build the wxWidgets dependency for a c++ project is VS Code on a Raspberry Pi using your linux.pdf.  But the configuration step failed with  `Code-unknown' not recognized, possibly due to the arm processor.

Here is the console output

pi@raspberrypi:~/VS Code Programs/CubicSDR/dep/linux/wxWidgets-3.1.5/linux_lib $ ../configure --with-gtk=3 --disable-shared --prefix=$(pwd)
configure: WARNING: you should use --build, --host, --target
configure: WARNING: you should use --build, --host, --target
configure: WARNING: invalid host type: Programs/CubicSDR/dep/linux/wxWidgets-3.1.5/linux_lib
checking build system type... Invalid configuration `Code': machine `Code-unknown' not recognized
configure: error: /bin/bash ../config.sub Code failed

Do you have any thought on how to fix this?

**Comment by huckor** [comment]
Hi,
seems to me your Raspberry Pi is missing some of the required packages. It's hard to say what's wrong without having Raspberry Pi on my hands.

What I found on internet is to first install this:
sudo apt-get install libgtk-3-dev build-essential checkinstall
and then configure like this:
../configure --disable-shared --enable-unicode --disable-debug

Please let me know if it's works for you.

**Comment by huckor** [comment]
Added document how to compile wxwidgets for Raspberri Pi running ARM version of Raspbian OS. Check /doc/raspbian.pdf for more info.
