### ISSUE TITLE
CMake is unable to find WxWidgets

### ISSUE THREAD

**Issue by freepcb** [huckor/wxwidgets-vscode#7]
Thanks for creating this project. I am using Ubuntu 20.04. I followed the instructions for compiling WxWidgets in the PDF and everything seemed to work OK. Then I tried to compile the "minimal" sample in VS Code, but CMake was unable to find the WxWidgets libraries. Here is the output:

[[cmake] CMake Error at /snap/cmake/1082/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
[cmake]   Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES) (Required is at
[cmake]   least version "3.1")
[cmake] Call Stack (most recent call first):
[cmake]   /snap/cmake/1082/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
[cmake]   /snap/cmake/1082/share/cmake-3.23/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
[cmake]   CMakeLists.txt:33 (find_package)

However, I was able to compile all of the samples using "make" from the command line.

Any help would be appreciated. Thanks.

**Comment by huckor** [comment]
Unfortunately I do not have any experience with cmake. Whole this project is made for make only.

**Comment by huckor** [comment]
Closing this issue because it is out of scope of this project.
