### ISSUE TITLE
/usr/bin/ld: cannot find -lwxregexu-3.1

### ISSUE THREAD

**Issue by dhjw** [huckor/wxwidgets-vscode#8]
On Ubuntu 20.04 I got the error seen in the title.

Removing `"-lwxregexu-3.1",` from the args in `.vscode/tasks.json` allowed the program to compile, but I wonder why it was missing.

**Comment by huckor** [comment]
What's wxwidgets version you used?

**Comment by dhjw** [comment]
I followed the doc/linux.pdf and got the latest download, so 3.1.6

**Comment by huckor** [comment]
According wxWidgets Change Log for version 3.1.6 wxregex library was removed. This can be cause why it's not possible to compile this project.

https://raw.githubusercontent.com/wxWidgets/wxWidgets/v3.1.6/docs/changes.txt

- wxRegEx now uses PCRE library, changing the meaning of some regular expressions, please see the "Changes" section in wxRegEx documentation for more details.

**Comment by huckor** [comment]
This bug is fixed in new release for wxWidgets 3.1.6.
